apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-backend
  template:
    metadata:
      labels:
        app: banking-backend
    spec:
      containers:
        - name: banking-backend
          image: banking-backend:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: "172.31.11.92"
          ports:
            - containerPort: 5000
