apiVersion: v1
kind: Service
metadata:
  name: banking-frontend-service
spec:
  type: NodePort
  selector:
    app: banking-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
